#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_DIR="$SCRIPT_DIR/source"
INDEX_FILE="$SOURCE_DIR/index.qmd"

cat > "$INDEX_FILE" <<'EOF'
<!--
This file is managed automatically by the Quarto render hooks in this project.
Do not edit this file directly.

During rendering, scripts/pre-render.sh replaces this file with profile-specific
content:
- html: source/index-html.qmd
- pdf:  source/ch01.qmd

After rendering, scripts/post-render.sh restores this placeholder so generated
chapter content is not left behind in the working tree.

Edit source/index-html.qmd or source/ch01.qmd instead.
-->

{{< include index-html.qmd >}}
EOF

echo "[post-render] restored managed placeholder in source/index.qmd"