# Two Tasks of Analysing Argumentation Structures {#sec-tasks}

<!-- EO
+ *Definition:* Justificatory relevance.
+ Two tasks of annotating argumentation structure: 
   1. Annotation of text segment as justificatory relevant.
-->
The simple dialogue from @sec-intro exemplifies that analysing the argumentation structure of a text involves two interdependent tasks: The annotation of text segments as argumentative components (i.e., the identification of argumentative units) and the categorisation of their interrelationships as support and attack relations.

## Identifying Argumentative Units

::: {.callout-tip #tip-first-task}
## Annotation of argumentative unit (first task)
You should annotate a text segment *x* as an *argumentative unit* if and only if one of the following holds:

1. *x* is presented as a justification for some other text segment *y*, or
2. *x* is the target of a justification or objection.
:::

Text segments that are formulated as arguments, reasons, objections, and refutations (i.e., argumentative components) are argumentative units. Text segments that are formulated with another function (e.g., as a question, an explanation, a description, a narrative, etc.) are not argumentative units. For instance, Audrey's critical questions are not argumentative units since they do not formulate reasons or objections on their own. But Clint's replies are argumentative units. Similarly, text segments that are the target of arguments, reasons, objections and refutations are argumentative units. While Clint's first statement ("I think we should all follow a vegetarian lifestyle.") is not presented as a justification for some claim, other statements are presented as a justification for it.

<!--
In what follows, we will often refer to o of reasons since objections and refutations can always be understood as *reasons against* something. If *x* is an objection to *y*, it can usually be understood as a reason that *y* is false, implausible, not acceptable, irrelevant or something similar. Additionally, we will neither distinguish between reasons and arguments on the one hand nor between different kinds of objections on the other hand.
-->

As the above example (see @fig-annot-guidelines-02) illustrates, an argumentative component can be the source *and* the target of argumentative relations. In other words, an argumentative unit can be presented as a justification for some other argumentative unit, and, at the same time, there can be another argumentative unit that is presented as a justification for it. For instance, in @fig-annot-guidelines-02 $R_1$ is presented as a reason for the main claim and is, additionally, justified by $R_2$.

Statements that are neither presented as a justification nor as an objection, but that are the target of a justification or objection, are also argumentative units. For instance, in @fig-annot-guidelines-02, the main claim is not presented as a justification for another statement but is the target of two reasons ($R_1$ and $R_4$). In the following, we will refer to argumentative components that have only incoming relations but no outgoing relations as *claims* or *main claims*.

It is also important to keep in mind that identifying argumentative units requires understanding the author's intentions and commitments. It is about understanding what is *presented* as a justification---independent of how you or someone else would evaluate the success of this presented justification. 

Finally, annotating argumentative units requires the individuation of argumentative components. As an annotator, you have to determine the start and endpoint of an argumentative unit by highlighting the corresponding text segment in some way. Argumentative units can encompass sentences, clauses or even smaller units, but they will not split words. Each argumentative unit should correspond to exactly one argumentative component. If a longer text segment formulates more than one argumentative component, you have to split up the longer text segment into smaller units.

## Identifying Support and Attack Relations
<!-- EO
   2. Determination of the justificatory role of justificatory relevant text segments (type and target).
-->
The first task (@tip-first-task) is the annotation of argumentative units; the second is the categorisation of their interrelationships by using attack and support relations.

::: {.callout-tip #tip-second-task}
## Identifying support and attack relations (second task)
Categorise for each argumentative unit its ingoing and outgoing support and attack relations.
:::

A text segment is an argumentative unit to the extent that it is presented as a reason (or objection) for some other text segment or as the target of a reason (or objection). As annotator, you have to categorise argumentative units as targets or sources of these relations and you should only use **two relations:**

1. **Support relation:** If an argumentative unit *x* is presented as justification for some other text segment *y*, we will categorise this justificatory relation as a*support relation* between *x* and *y* (represented by a green arrow from *x* to *y*), 
2. **Attack relation:** If an argumentative unit *x* is being presented as an objection or refutation of some other text segment *y*, we will categorise this justificatory relation as an *attack relation* between *x* and *y* (represented by a red arrow from *x* to *y*). 


![A schematic example of annotating the argumentation structure of a text. There are five argumentative units: The first one represents the main claim ($C$), which is supported by two reasons that are formulated by the second ($R_1$) and the fifth text segment ($R_4$). Both the third ($R_2$) and the fourth text segment ($R_3$) represent reasons against---that is, objections to the supporting reason $R_1$.](figures/fig-annot-guidelines-03){width=50%  #fig-annot-guidelines-03}

@fig-annot-guidelines-03 schematically illustrates the result of completing both tasks: an annotated text with identified argumentative units and with a categorisation of their interrelationships by support and attack relations. 

## Challenges in Annotating Argumentation Structures

<!-- EO
+ Interpretational nature of analysing argumentation structure.
-->
To analyse the argumentation structure of a text, you have to understand the conveyed meaning of the text. Since understanding a text's meaning is, to some extent, subjective and can differ from person to person, analysing the text's argumentation structure is also a process of interpretation that may allow for different interpretations. In other words, the analysis of argumentation structures is interpretational in nature. 

<!-- EO
+ Typical challenges of annotating the argumentation structure.
-->
You may encounter the following challenges when analysing the argumentation structure of a text:

+ First, you may find it difficult to decide whether a particular text segment is meant as a reason, objection or something else. Text segments often serve functions beyond simply formulating reasons and objections. The line between argumentative units and other types of text segments is blurry and continuous.
+ Second, it can be unclear to identify the exact beginning and end point of an argumentative unit.
+ Third, it can be ambiguous what the target of an argumentative unit is. In other words, it can be difficult to determine which other text segment is supposed to be justified or objected to by a particular argumentative unit. In some cases, the target of a reason or objection is not even explicitly formulated in the text.
+ Finally, you may wonder whether a text segment that is formulated as a justification represents just one or several argumentative components. We will refer to this latter challenge as the *problem of reason individuation*.

In the following, you will be provided with clarifications and maxims that will help you alleviate the problems of interpretive indeterminacy. First, we will better understand how to delineate argumentative units from other text segments. In other words, we will have to say more about what we mean by reasons, arguments and objections and how they can be distinguished from text segments with functions other than justifying something else (@sec-justificatory-relevance). We will then address the problem of individuating argumentative components (@sec-reason-individuation). Finally, we will look more closely at how to determine the targets of the support and attack relations (@sec-identifying-targets). There are also minor challenges that will be addressed in the frequently asked questions section at the end of these guidelines (@sec-freq-questions).