# Examples Used

To provide a realistic impression of how reasons are formulated in actual debates, this guideline will use examples from online articles on two debates: germline editing and affirmative action.


## Germline Editing (GE)
<!-- EO
+ Context knowledge: Germline editing.
-->
The GE debate concerns the use of the biotechnology CRISPR to modify the genes of gametes (eggs or sperm), fertilised eggs, and even human embryos. CRISPR is a gene-editing technology that can alter genetic material more precisely than older gene-modifying technologies. It can be applied to create genetically modified crops, develop vaccines, and treat genetic diseases. In contrast to somatic gene therapies, germline gene therapies target reproductive cells that eventually form embryos, sperm, and oocytes. One possible scenario is to use CRISPR in combination with in vitro fertilisation (IVF). After sperm is introduced into an egg in vitro, CRISPR is used to modify the genes of the fertilised egg to prevent genetic diseases such as Huntington's disease, Tay–Sachs disease and Duchenne muscular dystrophy. The important difference between somatic and germline gene therapies is that alterations of germline cells will be passed on to future generations. The GE debate gained prominence in 2018 when the Chinese researcher He Jiankui claimed that he had used CRISPR to edit the genomes of the embryos of two twin girls born in 2018. Scientists and ethicists worldwide condemned He's actions and raised concerns about unknown risks and side effects. The current GE debate is about the following central questions:

+ Should we use GE in the future for therapeutic means? Under which conditions should GE be permitted as a therapy?
+ Should we research germline editing technologies by using embryos? Under which conditions should we allow scientists to alter embryos' genes for purposes of research? How should we regulate such research?

## Affirmative Action
<!-- EO
+ Context knowledge: Affirmative action.
-->
Affirmative action is an umbrella term for practices and regulations that seek to eliminate underrepresentation in education, employment, and politics resulting from historical discrimination based on gender, race, or religion. Affirmative action was first introduced in the United States in 1961 by President John F. Kennedy's Executive Order 10925, which required federal contractors "to ensure that applicants are treated equally without regard to race, colour, religion, sex, or national origin." Measures of affirmative action can differ in the means they employ and in the targeted groups.

The text snippets we will analyse concern affirmative action in college admissions at universities in the United States. The main question in this debate is whether it is permissible to include race-based categories as admission criteria to promote diversity on campus and counteract the underrepresentation of racial minorities at elite universities.